coverage:
  status:
    project:
      csharp:
        flags: 
          - csharp_unit
          - csharp_integration
        paths: 
          - MyCSharp/
      js:
        flags: 
          - js_unit
        paths: 
          - myjs/